#默认访问端口server:
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyrule?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#  Jpa相关配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    必须配置方言为InnoDB,否则数据库外键无法使用
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# Netty相关配置
netty:
  server:
    auto-start: 1
    serverName: Netty服务器
    serverPort: 13333

#Pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

